# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shc_MDSeparation <- function(mean1, covariance1, virtualVariance1, N1, isInversion1, th1, mean2, covariance2, virtualVariance2, N2, isInversion2, th2) {
    .Call('_SHClus_shc_MDSeparation', PACKAGE = 'SHClus', mean1, covariance1, virtualVariance1, N1, isInversion1, th1, mean2, covariance2, virtualVariance2, N2, isInversion2, th2)
}

shc_MutualMinMahalanobis <- function(mean1, covariance1, virtualVariance1, N1, isInversion1, mean2, covariance2, virtualVariance2, N2, isInversion2) {
    .Call('_SHClus_shc_MutualMinMahalanobis', PACKAGE = 'SHClus', mean1, covariance1, virtualVariance1, N1, isInversion1, mean2, covariance2, virtualVariance2, N2, isInversion2)
}

shc_CalculateNewMean <- function(mean, newElement, N) {
    .Call('_SHClus_shc_CalculateNewMean', PACKAGE = 'SHClus', mean, newElement, N)
}

shc_CalculateCovariance <- function(oldMean, newMean, oldCovariance, N, newElement, isInversion) {
    .Call('_SHClus_shc_CalculateCovariance', PACKAGE = 'SHClus', oldMean, newMean, oldCovariance, N, newElement, isInversion)
}

